name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build app/CdkTest --file app/CdkTest/CdkTest.Web/Dockerfile --tag cdk-test-web:latest
    - name: Push to Amazon ECR
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: us-west-1
        local-image: cdk-test-web:latest
        image: cdk_test_ecr_repo:latest